import PBIcon from "./images/PBIcon.svg";
import Bug from "./images/BugIC.png";
import Dark from "./images/DarkIC.png";
import Dragon from "./images/DragonIC.png";
import Electric from "./images/ElectricIC.png";
import Fairy from "./images/FairyIC.png";
import Fighting from "./images/FightingIC.png";
import Fire from "./images/FireIC.png";
import Flying from "./images/FlyingIC.png";
import Ghost from "./images/GhostIC.png";
import Grass from "./images/GrassIC.png";
import Ground from "./images/GroundIC.png";
import Ice from "./images/IceIC.png";
import Normal from "./images/NormalIC.png";
import Poison from "./images/PoisonIC.png";
import Psychic from "./images/PsychicIC.png";
import Rock from "./images/RockIC.png";
import Steel from "./images/SteelIC.png";
import Water from "./images/WaterIC.png";
import MegaEvol from "./images/megaevol.svg";

export { PBIcon, Bug, Dark, Dragon, Electric, Fairy, Fighting, Fire, Flying, Ghost, Grass, Ground, Ice, Normal, Poison, Psychic, Rock, Steel, Water, MegaEvol };
