export const forms = {
  aegislash: ["aegislash-shield", "aegislash-blade"],
  arcanine: ["arcanine", "arcanine-hisui"],
  articuno: ["articuno", "articuno-galar"],
  avalugg: ["avalugg", "avalugg-hisui"],
  basculegion: ["basculegion-male", "basculegion-female"],
  basculin: ["basculin-red-striped", "basculing-blue-striped", "basculin-white-striped"],
  braviary: ["braviary", "braviary-hisui"],
  calyrex: ["calyrex", "calyrex-ice", "calyrex-shadow"],
  castform: ["castform", "castform-sunny", "castform-rainy", "castform-snowy"],
  cherrim: ["cherrim"],
  corsola: ["corsola", "corsola-galar"],
  darmanitan: ["darmanitan-standard", "darmanitan-zen", "darmanitan-galar-standard", "darmanitan-galar-zen"],
  darumaka: ["darumaka", "darumaka-galar"],
  decidueye: ["decidueye", "decidueye-hisui"],
  deoxys: ["deoxys-normal", "deoxys-attack", "deoxys-defense", "deoxys-speed"],
  dialga: ["dialga", "dialga-origin"],
  diglett: ["diglett", "diglett-alola"],
  dudunsparce: ["dudunsparce-two-segment"],
  dugtrio: ["dugtrio", "dugtrio-alola"],
  eiscue: ["eiscue-ice", "eiscue-noice"],
  electrode: ["electrode", "electrode-hisui"],
  enamorus: ["enamorus-incarnate", "enamorus-therian"],
  eternatus: ["eternatus", "eternatus-eternamax"],
  exeggutor: ["exeggutor", "exeggutor-alola"],
  farfetchd: ["farfetchd", "farfetchd-galar"],
  flabébé: ["flabebe"],
  floette: ["floette", "floette-eternal"],
  geodude: ["geodude", "geodude-alola"],
  gimmighoul: ["gimmighoul", "gimmighoul-roaming"],
  giratina: ["giratina-altered", "giratina-origin"],
  golem: ["golem", "golem-alola"],
  goodra: ["goodra", "goodra-hisui"],
  gourgeist: ["gourgeist-small", "gourgeist-average", "gourgeist-large", "gourgeist-super"],
  graveler: ["graveler", "graveler-alola"],
  greninja: ["greninja", "greninja-ash"],
  grimer: ["grimer", "grimer-alola"],
  groudon: ["groudon", "groudon-primal"],
  growlithe: ["growlithe", "growlithe-hisui"],
  hoopa: ["hoopa", "hoopa-unbound"],
  indeedee: ["indeedee-male", "indeedee-female"],
  keldeo: ["keldeo-ordinary", "keldeo-resolute"],
  kyogre: ["kyogre", "kyogre-primal"],
  kyurem: ["kyurem", "kyurem-white", "kyurem-black"],
  landorus: ["landorus-incarnate", "landorus-therian"],
  lilligant: ["lilligant", "lilligant-hisui"],
  linoone: ["linoone", "linoone-galar"],
  lycanroc: ["lycanroc-midday", "lycanroc-midnight", "lycanroc-dusk"],
  marowak: ["marowak", "marowak-alola"],
  maushold: ["maushold-family-of-four"],
  meloetta: ["meloetta-aria", "meloetta-pirouette"],
  meowstic: ["meowstic-male", "meowstic-female"],
  meowth: ["meowth", "meowth-alola", "meowth-galar"],
  mimikyu: ["mimikyu-disguised"],
  minior: ["minior-red-meteor", "minior-red"],
  moltres: ["moltres", "moltres-galar"],
  morpeko: ["morpeko-full-belly"],
  "mr-mime": ["mr-mime", "mr-mime-galar"],
  muk: ["muk", "muk-alola"],
  necrozma: ["necrozma", "necrozma-dusk", "necrozma-dawn", "necrozma-ultra"],
  "nidoran♂": ["nidoran-m"],
  "nidoran♀": ["nidoran-f"],
  ninetales: ["ninetales", "ninetales-alola"],
  ogerpon: ["ogerpon", "ogerpon-wellspring-mask", "ogerpon-hearthflame-mask", "ogerpon-cornerstone-mask"],
  oinkologne: ["oinkologne-male", "oinkologne-female"],
  oricorio: ["oricorio-baile", "oricorio-pom-pom", "oricorio-pau", "oricorio-sensu"],
  palafin: ["palafin-zero", "palafin-hero"],
  palkia: ["palkia", "palkia-origin"],
  persian: ["persian", "persian-alola"],
  ponyta: ["ponyta", "ponyta-galar"],
  pumpkaboo: ["pumpkaboo-small", "pumpkaboo-average", "pumpkaboo-large", "pumpkaboo-super"],
  qwilfish: ["qwilfish", "qwilfish-hisui"],
  raichu: ["raichu", "raichu-alola"],
  rapidash: ["rapidash", "rapidash-galar"],
  raticate: ["raticate", "raticate-alola"],
  rattata: ["rattata", "rattata-alola"],
  rotom: ["rotom", "rotom-heat", "rotom-wash", "rotom-frost", "rotom-fan", "rotom-mow"],
  samurott: ["samurott", "samurott-hisui"],
  sandshrew: ["sandshrew", "sandshrew-alola"],
  sandslash: ["sandslash", "sandslash-alola"],
  shaymin: ["shaymin-land", "shaymin-sky"],
  sliggoo: ["sliggoo", "sliggoo-hisui"],
  slowbro: ["slowbro", "slowbro-galar"],
  slowking: ["slowking", "slowking-galar"],
  slowpoke: ["slowpoke", "slowpoke-galar"],
  sneasel: ["sneasel", "sneasel-hisui"],
  squawkabilly: ["squawkabilly-green-plumage", "squawkabilly-blue-plumage", "squawkabilly-yellow-plumage", "squawkabilly-white-plumage"],
  stunfisk: ["stunfisk", "stunfisk-galar"],
  tatsugiri: ["tatsugiri-curly"],
  tauros: ["tauros", "tauros-paldea-combat-breed", "tauros-paldea-blaze-breed", "tauros-paldea-aqua-breed"],
  terapagos: ["terapagos", "terapagos-terastal", "terapagos-stellar"],
  thundurus: ["thundurus-incarnate", "thundurus-therian"],
  tornadus: ["tornadus-incarnate", "tornadus-therian"],
  toxtricity: ["toxtricity-amped", "toxtricity-low-key"],
  typhlosion: ["typhlosion", "typhlosion-hisui"],
  ursaluna: ["ursaluna", "ursaluna-bloodmoon"],
  urshifu: ["urshifu-single-strike", "urshifu-rapid-strike"],
  voltorb: ["voltorb", "voltorb-hisui"],
  vulpix: ["vulpix", "vulpix-alola"],
  wishiwashi: ["wishiwashi-solo", "wishiwashi-school"],
  wooper: ["wooper", "wooper-paldea"],
  wormadam: ["wormadam-plant", "wormadam-sandy", "wormadam-trash"],
  yamask: ["yamask", "yamask-galar"],
  zacian: ["zacian", "zacian-crowned"],
  zamazenta: ["zamazenta", "zamazenta-crowned"],
  zapdos: ["zapdos", "zapdos-galar"],
  zigzagoon: ["zigzagoon", "zigzagoon-galar"],
  zoroark: ["zoroark", "zoroark-hisui"],
  zorua: ["zorua", "zorua-hisui"],
  zygarde: ["zygarde-10", "zygarde-50", "zygarde-complete"],
};
