export const fixer = {
  regionals: [],
  alola: [],
  diglett: ["diglett", "diglett-alola"],
  dugtrio: ["dugtrio", "dugtrio-alola"],
  exeggutor: ["exeggutor", "exeggutor-alola"],
  geodude: ["geodude", "geodude-alola"],
  golem: ["golem", "golem-alola"],
  graveler: ["graveler", "graveler-alola"],
  grimer: ["grimer", "grimer-alola"],
  marowak: ["marowak", "marowak-alola"],
  muk: ["muk", "muk-alola"],
  ninetales: ["ninetales", "ninetales-alola"],
  persian: ["persian", "persian-alola"],
  raichu: ["raichu", "raichu-alola"],
  raticate: ["raticate", "raticate-alola"],
  rattata: ["rattata", "rattata-alola"],
  sandshrew: ["sandshrew", "sandshrew-alola"],
  sandslash: ["sandslash", "sandslash-alola"],
  vulpix: ["vulpix", "vulpix-alola"],
  galar: [],
  corsola: ["corsola", "corsola-galar"],
  darumaka: ["darumaka", "darumaka-galar"],
  articuno: ["articuno", "articuno-galar"],
  farfetchd: ["farfetchd", "farfetchd-galar"],
  linoone: ["linoone", "linoone-galar"],
  moltres: ["moltres", "moltres-galar"],
  "mr-mime": ["mr-mime", "mr-mime-galar"],
  ponyta: ["ponyta", "ponyta-galar"],
  rapidash: ["rapidash", "rapidash-galar"],
  slowking: ["slowking", "slowking-galar"],
  slowpoke: ["slowpoke", "slowpoke-galar"],
  stunfisk: ["stunfisk", "stunfisk-galar"],
  yamask: ["yamask", "yamask-galar"],
  zapdos: ["zapdos", "zapdos-galar"],
  zigzagoon: ["zigzagoon", "zigzagoon-galar"],
  hisui: [],
  arcanine: ["arcanine", "arcanine-hisui"],
  avalugg: ["avalugg", "avalugg-hisui"],
  braviary: ["braviary", "braviary-hisui"],
  decidueye: ["decidueye", "decidueye-hisui"],
  electrode: ["electrode", "electrode-hisui"],
  goodra: ["goodra", "goodra-hisui"],
  growlithe: ["growlithe", "growlithe-hisui"],
  lilligant: ["lilligant", "lilligant-hisui"],
  qwilfish: ["qwilfish", "qwilfish-hisui"],
  samurott: ["samurott", "samurott-hisui"],
  sliggoo: ["sliggoo", "sliggoo-hisui"],
  sneasel: ["sneasel", "sneasel-hisui"],
  typhlosion: ["typhlosion", "typhlosion-hisui"],
  voltorb: ["voltorb", "voltorb-hisui"],
  zoroark: ["zoroark", "zoroark-hisui"],
  zorua: ["zorua", "zorua-hisui"],
  paldea: [],
  tauros: ["tauros", "tauros-paldea-combat-breed", "tauros-paldea-blaze-breed", "tauros-paldea-aqua-breed"],
  wooper: ["wooper", "wooper-paldea"],
  multiregions: [],
  meowth: ["meowth", "meowth-alola", "meowth-galar"],
  miltiforms: [],
  aegislash: ["aegislash-shield", "aegislash-blade"],
  basculegion: ["basculegion-male", "basculegion-female"],
  basculin: ["basculin-red-striped", "basculing-blue-striped", "basculin-white-striped"],
  calyrex: ["calyrex", "calyrex-ice", "calyrex-shadow"],
  castform: ["castform", "castform-sunny", "castform-rainy", "castform-snowy"],
  cherrim: ["cherrim"],
  deoxys: ["deoxys-normal", "deoxys-attack", "deoxys-defense", "deoxys-speed"],
  dialga: ["dialga", "dialga-origin"],
  dudunsparce: ["dudunsparce-two-segment"],
  eiscue: ["eiscue-ice", "eiscue-noice"],
  enamorus: ["enamorus-incarnate", "enamorus-therian"],
  eternatus: ["eternatus", "eternatus-eternamax"],
  flabébé: ["flabebe"],
  floette: ["floette", "floette-eternal"],
  gimmighoul: ["gimmighoul", "gimmighoul-roaming"],
  giratina: ["giratina-altered", "giratina-origin"],
  gourgeist: ["gourgeist-small", "gourgeist-average", "gourgeist-large", "gourgeist-super"],
  greninja: ["greninja", "greninja-ash"],
  groudon: ["groudon", "groudon-primal"],
  hoopa: ["hoopa", "hoopa-unbound"],
  indeedee: ["indeedee-male", "indeedee-female"],
  keldeo: ["keldeo-ordinary", "keldeo-resolute"],
  kyogre: ["kyogre", "kyogre-primal"],
  kyurem: ["kyurem", "kyurem-white", "kyurem-black"],
  landorus: ["landorus-incarnate", "landorus-therian"],
  lycanroc: ["lycanroc-midday", "lycanroc-midnight", "lycanroc-dusk"],
  maushold: ["maushold-family-of-four"],
  meloetta: ["meloetta-aria", "meloetta-pirouette"],
  meowstic: ["meowstic-male", "meowstic-female"],
  mimikyu: ["mimikyu-disguised"],
  minior: ["minior-red-meteor", "minior-red"],
  morpeko: ["morpeko-full-belly"],
  necrozma: ["necrozma", "necrozma-dusk", "necrozma-dawn", "necrozma-ultra"],
  nidoran: ["nidoran-m", "nidoran-f"],
  ogerpon: ["ogerpon", "ogerpon-wellspring-mask", "ogerpon-hearthflame-mask", "ogerpon-cornerstone-mask"],
  oinkologne: ["oinkologne-male", "oinkologne-female"],
  oricorio: ["oricorio-baile", "oricorio-pom-pom", "oricorio-pau", "oricorio-sensu"],
  palafin: ["palafin-zero", "palafin-hero"],
  palkia: ["palkia", "palkia-origin"],
  pumpkaboo: ["pumpkaboo-small", "pumpkaboo-average", "pumpkaboo-large", "pumpkaboo-super"],
  rotom: ["rotom", "rotom-heat", "rotom-wash", "rotom-frost", "rotom-fan", "rotom-mow"],
  shaymin: ["shaymin-land", "shaymin-sky"],
  squawkabilly: ["squawkabilly-green-plumage", "squawkabilly-blue-plumage", "squawkabilly-yellow-plumage", "squawkabilly-white-plumage"],
  tatsugiri: ["tatsugiri-curly"],
  terapagos: ["terapagos", "terapagos-terastal", "terapagos-stellar"],
  thundurus: ["thundurus-incarnate", "thundurus-therian"],
  tornadus: ["tornadus-incarnate", "tornadus-therian"],
  toxtricity: ["toxtricity-amped", "toxtricity-low-key"],
  ursaluna: ["ursaluna", "ursaluna-bloodmoon"],
  urshifu: ["urshifu-single-strike", "urshifu-rapid-strike"],
  wishiwashi: ["wishiwashi-solo", "wishiwashi-school"],
  wormadam: ["wormadam-plant", "wormadam-sandy", "wormadam-trash"],
  zacian: ["zacian", "zacian-crowned"],
  zamazenta: ["zamazenta", "zamazenta-crowned"],
  zygarde: ["zygarde-10", "zygarde-50", "zygarde-complete"],
  megaevolutions: [],
  venusaur: ["venusaur", "venusaur-mega"],
  charizard: ["charizard", "charizard-mega-x", "charizard-mega-y"],
  blastoise: ["blastoise", "blastoise-mega"],
  alakazam: ["alakazam", "alakazam-mega"],
  gengar: ["gengar", "gengar-mega"],
  kangaskhan: ["kangaskhan", "kangaskhan-mega"],
  pinsir: ["pinsir", "pinsir-mega"],
  gyarados: ["gyarados", "gyarados-mega"],
  aerodactyl: ["aerodactyl", "aerodactyl-mega"],
  mewtwo: ["mewtwo", "mewtwo-mega-x", "mewtwo-mega-y"],
  ampharos: ["ampharos", "ampharos-mega"],
  scizor: ["scizor", "scizor-mega"],
  heracross: ["heracross", "heracross-mega"],
  houndoom: ["houndoom", "houndoom-mega"],
  tyranitar: ["tyranitar", "tyranitar-mega"],
  blaziken: ["blaziken", "blaziken-mega"],
  gardevoir: ["gardevoir", "gardevoir-mega"],
  mawile: ["mawile", "mawile-mega"],
  aggron: ["aggron", "aggron-mega"],
  medicham: ["medicham", "medicham-mega"],
  manetric: ["manetric", "manetric-mega"],
  banette: ["banette", "banette-mega"],
  absol: ["absol", "absol-mega"],
  latias: ["latias", "latias-mega"],
  latios: ["latios", "latios-mega"],
  garchomp: ["garchomp", "garchomp-mega"],
  lucario: ["lucario", "lucario-mega"],
  abomasnow: ["abomasnow", "abomasnow-mega"],
  beedrill: ["beedrill", "beedrill-mega"],
  pidgeot: ["pidgeot", "pidgeot-mega"],
  steelix: ["steelix", "steelix-mega"],
  sceptile: ["sceptile", "sceptile-mega"],
  swampert: ["swampert", "swampert-mega"],
  sableye: ["stableye", "sableye-mega"],
  sharpedo: ["sharpedo", "sharpedo-mega"],
  camerupt: ["camerupt", "camerupt-mega"],
  altaria: ["altaria", "altaria-mega"],
  glalie: ["glalie", "glalie-mega"],
  salamence: ["salamence", "salamence-mega"],
  metagross: ["metagross", "metagross-mega"],
  rayquaza: ["rayquaza", "rayquaza-mega"],
  lopunny: ["lopunny", "lopunny-mega"],
  gallade: ["gallade", "gallade-mega"],
  audino: ["audino", "audino-mega"],
  diancie: ["diancie", "diancie-mega"],
  multiclassed: [],
  slowbro: ["slowbro", "slowbro-galar", "slowbro-mega"],
  darmanitan: ["darmanitan-standard", "darmanitan-zen", "darmanitan-galar-standard", "darmanitan-galar-zen"],
};
