export const fixer = {
  generics: "",
  farfetchd: "Farfetch'd",
  "farfetchd-galar": "Galarian Form",
  "mr-mime": "Mr. Mime",
  "mr-mime-galar": "Galarian Form",
  "tauros-paldea-combat-breed": "Combat Breed",
  "tauros-paldea-blaze-breed": "Blaze Breed",
  "tauros-paldea-aqua-breed": "Aqua Breed",
  "basculin-red-striped": "Red Striped",
  "basculin-blue-striped": "Blue Striped",
  "basculin-white-striped": "White Striped",
  "calyrex-ice": "Ice Rider",
  "calyrex-shadow": "Shadow Rider",
  "castform-sunny": "Sunny Weather",
  "castform-rainy": "Rainy Weather",
  "castform-snowy": "Snowy Weather",
  "deoxys-normal": "Normal Forme",
  "deoxys-attack": "Attack Forme",
  "deoxys-defense": "Defense Forme",
  "deoxys-speed": "Speed Forme",
  "dialga-origin": "Origin Forme",
  "eiscue-ice": "Ice Face",
  "eiscue-noice": "Noice Face",
  "enamorus-incarnate": "Incarnate",
  "enamorus-therian": "Therian",
  "eternatus-eternamax": "Eternamax",
  gimmighoul: "Chest Form",
  "gimmighoul-roaming": "Roaming Form",
  "giratina-altered": "Altered Forme",
  "giratina-origin": "Origin Forme",
  "gourgeist-small": "Small Size",
  "gourgeist-average": "Average Size",
  "gourgeist-large": "Large Size",
  "gourgeist-super": "Super Size",
  "greninja-ash": "Ash-Greninja",
  "groudon-primal": "Primal",
  hoopa: "Confined",
  "hoopa-unbound": "Unbound",
  "indeedee-male": "Male",
  "indeedee-female": "Female",
  "keldeo-ordinary": "Ordinary",
  "keldeo-resolute": "Resolute",
  "kyogre-primal": "Primal",
  "kyurem-white": "White Absofusion",
  "kyurem-black": "Black Absofusion",
  "landorus-incarnate": "Incarnate",
  "landorus-therian": "Therian",
  "lycanroc-midday": "Midday",
  "lycanroc-midnight": "Midnight",
  "lycanroc-dusk": "Dusk",
  "meloetta-aria": "Aria Forme",
  "meloetta-pirouette": "Pirouette Forme",
  "meowstic-male": "Male",
  "meowstic-female": "Female",
  "minior-red-meteor": "Meteor",
  "minior-red": "Core",
  "necrozma-dusk": "Dusk Mane",
  "necrozma-dawn": "Dawn Wings",
  "necrozma-ultra": "Ultra",
  "nidoran-m": "Male",
  "nidoran-f": "Female",
  ogerpon: "Teal Mask",
  "ogerpon-wellspring-mask": "Wellspring Mask",
  "ogerpon-hearthflame-mask": "Hearthflame Mask",
  "ogerpon-cornerstone-mask": "Cornerstone Mask",
  "oinkologne-male": "Male",
  "oinkologne-female": "Female",
  "oricorio-baile": "Baile Style",
  "oricorio-pom-pom": "Pom-Pom Style",
  "oricorio-pau": "Pa'u Style",
  "oricorio-sensu": "Sensu Style",
  "palafin-zero": "Zero",
  "palafin-hero": "Hero",
  "palkia-origin": "Origin",
  "pumpkaboo-small": "Small Size",
  "pumpkaboo-average": "Average Size",
  "pumpkaboo-large": "Large Size",
  "pumpkaboo-super": "Super Size",
  "rotom-heat": "Heat Rotom",
  "rotom-wash": "Wash Rotom",
  "rotom-frost": "Frost Rotom",
  "rotom-fan": "Fan Rotom",
  "rotom-mow": "Mow Rotom",
  "shaymin-land": "Land Forme",
  "shaymin-sky": "Sky Forme",
  "squawkabilly-green-plumage": "Green Plumage",
  "squawkabilly-blue-plumage": "Blue Plumage",
  "squawkabilly-yellow-plumage": "Yellow Plumage",
  "squawkabilly-white-plumage": "White Plumage",
  "tatsugiri-curly": "Curly",
  "tatsugiri-droopy": "Droopy",
  "tatsugiri-stretchy": "Stretchy",
  "terapagos-terastal": "Terastal Form",
  "terapagos-stellar": "Stellar Form",
  "thundurus-incarnate": "Incarnate",
  "thundurus-therian": "Therian",
  "tornadus-incarnate": "Incarnate",
  "tornadus-therian": "Therian",
  "toxtricity-amped": "Amped Form",
  "toxtricity-low-key": "Low Key Form",
  "ursaluna-bloodmoon": "Bloodmoon",
  "urshifu-single-strike": "Single Strike Style",
  "urshifu-rapid-strike": "Rapid Strike Style",
  "wishiwashi-solo": "Solo",
  "wishiwashi-school": "School",
  "wormadam-plant": "Plant Cloak",
  "wormadam-sandy": "Sandy Cloak",
  "wormadam-trash": "Trash Cloak",
  zacian: "Hero of Many Battles",
  "zacian-crowned": "Crowned Sword",
  zamazenta: "Hero of Many Battles",
  "zamazenta-crowned": "Crowned Shield",
  "zygarde-10": "10% Forme",
  "zygarde-50": "50% Forme",
  "zygarde-complete": "Complete Forme",
  "darmanitan-standard": "Standard Mode",
  "darmanitan-zen": "Zen Mode",
  "darmanitan-galar-standard": "Galarrian Standard Mode",
  "darmanitan-galar-zen": "Galarrian Zen Mode",
};
