export const fixer = {
  "mr-mime": "Mr. MIME",
  "mr-mime-galar": "Mr. MIME",
  flabebe: "FLABÉBÉ",
  "nidoran-m": "NIDORAN♂",
  "nidoran-f": "NIDORAN♀",
  "ho-oh": "HO-OH",
  "porygon-z": "PORYGON-Z",
  "type-null": "TYPE: NULL",
  "jangmo-o": "JANGMO-O",
  "hakamo-o": "HAKAMO-O",
  "kommo-o": "KOMMO-O",
  "tapu-koko": "TAPU KOKO",
  "tapu-lele": "TAPU LELE",
  "tapu-bulu": "TAPU BULU",
  "tapu-fini": "TAPU FINI",
  farfetchd: "FARFETCH'D",
  sirfetchd: "SIRFETCH'D",
  "mr-rime": "Mr. RIME",
  "great-tusk": "GREAT TUSK",
  "scream-tail": "SCREAM TAIL",
  "brute-bonnet": "BRUTE BONNET",
  "flutter-mane": "FLUTTER MANE",
  "slither-wing": "SLITHER WING",
  "sandy-shocks": "SANDY SHOCKS",
  "iron-treads": "IRON TREADS",
  "iron-bundle": "IRON BUNDLE",
  "iron-hands": "IRON HANDS",
  "iron-jugulis": "IRON JUGULIS",
  "iron-moth": "IRON MOTH",
  "iron-thorns": "IRON THORNS",
  "wo-chien": "WO-CHIEN",
  "chien-pao": "CHIEN-PAO",
  "ting-lu": "TING-LU",
  "chi-yu": "CHI-YU",
  "roaring-moon": "ROARING MOON",
  "iron-valiant": "IRON VALIANT",
  "walking-wake": "WALING WAKE",
  "iron-leaves": "IRON LEAVES",
  "gouging-fire": "GOUGING FIRE",
  "raging-bolt": "RAGING BOLT",
  "iron-boulder": "IRON BOULDER",
  "iron-crown": "IRON CROWN",
};
